### ISSUE TITLE
Error on compilation after upgrade V1.0.8

### ISSUE THREAD

**Issue by Rickgr** [heagoo/apk_builder_tutorial#2]
Hello and thx for Apk Builder :)
After upgrade the new version V1.0.8 i don't cant compil old or new projects.
The message error is :

UNEXPECTED TOP-LEVEL ERROR:
java.lang.NoSuchFieldError: No field callSiteIds of type Lcom/android/dex/TableOfContents$Section; in class Lcom/android/dex/TableOfContents; or its superclasses (declaration of 'com.android.dex.TableOfContents' appears in /system/framework/core-libart.jar)
	at com.android.dx.merge.IndexMap.<init>(IndexMap.java:84)
	at com.android.dx.merge.DexMerger.<init>(DexMerger.java:106)
	at com.android.dx.merge.DexMerger.<init>(DexMerger.java:92)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:503)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:333)
	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
	at com.android.dx.command.dexer.Main.main(Main.java:244)
	at com.android.dx.command.Main.main(Main.java:95)

Can you help me please for the solution please

Thx

**Comment by heagoo** [comment]
oh, my mistake (I didn't aware that as my phone works)
I have to rename the package name of dx, will update it.

**Comment by Rickgr** [comment]
Thanks for the patch this one works since the last update. Super reactivite on your part. Thanks again for your application.

**Comment by heagoo** [comment]
good to hear that :)
