### ISSUE TITLE
Unable to compile flashlight demo

### ISSUE THREAD

**Issue by justbittin** [heagoo/apk_builder_tutorial#8]
Dalvik VM unable to locate class 'dx/dx/command/Main'
java.lang.NoClassDefFoundError: dx/dx/command/Main
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: dx.dx.command.Main
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	... 1 more

The terminal stops at 'Compiling Java...'  ( I have to ctrl-c)

Suggestions?

**Comment by justbittin** [comment]
For clarity, the error is from 'Build' button when project is open.
